### ISSUE TITLE
Contatto esercizi nimbella

### ISSUE THREAD

**Issue by sciabarracom** [Tpierluigi/Gestione20#1]
Ciao Pierlugi scusa se ti scrivo qui ma non so in che altro modo contattarti.
Ha condiviso con michele-sciabarra, devi usare lo user sciabarracom per farmi vedere il tuo lavoro. Grazie scusa rimuovi pure questo ticket.

**Comment by Tpierluigi** [comment]
grazie, non mi ricordavo dell'altro utente... :-)

adesso sistemo.

Pier

Il giorno lun 8 feb 2021 alle ore 10:20 Michele Sciabarra <
notifications@github.com> ha scritto:
